"""Update product and supplier models

Revision ID: 755b5166a7b1
Revises: 7ce3bf6d0061
Create Date: 2026-07-27 13:59:55.650891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755b5166a7b1'
down_revision = '7ce3bf6d0061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
    "fk_products_supplier_id",
    "suppliers",
    ["supplier_id"],
    ["id"]
)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('supplier_id')

    # ### end Alembic commands ###
